image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y python3 python3-tk python3-pip curl git
  - pip3 install pytest wheel flake8
  - cd ..
  - git clone https://github.com/ReNom-dev-team/ReNom.git
  - pip3 install numpy
  - pip3 install -r ReNom/requirements.txt
  - cd ReNomCN
  - pip3 install -e .

flake8:
  script:
    - flake8

pytest:
  script:
    - pytest

packages:
  script:
    - python3 setup.py bdist_wheel
    - mkdir -p public/$CI_COMMIT_TAG/bin
    - cp dist/* public/$CI_COMMIT_TAG/bin
    - ls public/$CI_COMMIT_TAG/bin

  artifacts:
    paths:
    - public/$CI_COMMIT_TAG/

  # only:
  #   - /^release\/.*$/
